import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
import Navbar from "./component/Home/navbar";
import ScrollButtons from "./component/scrollButtons";
import Join from "./component/Home/join";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Join />

        <ScrollButtons />
      </body>
    </html>
  );
}
